### ISSUE TITLE
wiki-安装文档改进

### ISSUE THREAD

**Issue by michealzh** [qit-team/snow#1]
安装文档wiki中 https://github.com/qit-team/snow/wiki/install 中下载源码包步骤

```
git clone git@github.com/qit-team/snow.git my-project
```

执行上面的命令会提示`fatal: 仓库 'git@github.com/qit-team/snow.git' 不存在`

需要更新为：

```
git clone git@github.com:qit-team/snow.git my-project
```

**Comment by hetiansu5** [comment]
谢谢指出，已fix~
