### ISSUE TITLE
缺少 tests

### ISSUE THREAD

**Issue by shaunthegeek** [qit-team/snow#11]
作为正式可上线的框架，应带着完善的 tests 代码。通过 https://codecov.io 可显示测试覆盖率。

参考我的项目：https://github.com/wifidog/wifidog-auth-laravel

**Comment by ACoderHIT** [comment]
您好，我这边正在逐步的完善单测，最近从snow-core入手，目前snow-core的单测覆盖率已经达到75%【用go tool cover统计】，后续会将snow的单测补充进来，感谢您的建议
